name: ROS2:Humble(22.04)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os-ros: 
          - { image: 'ubuntu:jammy', ros: 'humble' }

    container:
      image: ${{matrix.os-ros.image}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up ROS
        uses: ros-tooling/setup-ros@v0.6
        with:
          required-ros-distributions: ${{matrix.os-ros.ros}}

      - name: Install Dependencies
        run: sudo apt-get install qtbase5-dev qt5-qmake libqt5svg5-dev qtbase5-dev-tools qtbase5-private-dev qt5* libeigen3-dev libgtest-dev libsdl-image1.2-dev libsdl1.2-dev -y

      - name: Update gtest
        run: |
          wget https://github.com/google/googletest/archive/refs/tags/release-1.12.1.tar.gz \
          && tar -zxvf release-1.12.1.tar.gz \
          && cd googletest-release-1.12.1 \
          && mkdir build \
          && cd build \
          && cmake .. \
          && make -j$(nproc) \
          && sudo make install

      - name: Build
        run: |
          /bin/bash -c \
          "source /opt/ros/${{matrix.os-ros.ros}}/setup.bash \
          && sudo apt-get install qtbase5-dev qt5-qmake libqt5svg5-dev qtbase5-dev-tools qtbase5-private-dev qt5* libeigen3-dev libgtest-dev -y  \
          && rm -rf build \
          && mkdir build/ \
          && cd build/ \
          && cmake .. -DBUILD_WITH_TEST=ON\
          && make -j$(nproc) \
          && make install"
      - name: Test
        run: |
          /bin/bash -c \
          "source /opt/ros/${{matrix.os-ros.ros}}/setup.bash \
          && cd build \
          && make test"